spring:
  profiles:
    active: development
  datasource:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health

---

spring:
  profiles: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./devdb
    username: dbuser
    password: dbpass

---

spring:
  profiles: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./testdb
    username: dbuser
    password: dbpass
---

  spring:
    profiles: test
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:h2:./testdb
      username: dbuser
      password: dbpass