spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./devdb
    username: dbuser
    password: dbpass
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
